name: Coverage

on:
  push:
    branches:
      - '*'

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'

    - name: Install dependencies
      run: rm -rf node_modules yarn.lock cache artifacts typechain typechain-types && yarn

    - name: Coverage
      run: npx hardhat coverage
